version: "3.8"

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    ports:
      - "9000:9000"
    tty: true
    networks:
      moodle:
        ipv4_address: 10.1.1.10

  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      moodle:
        ipv4_address: 10.1.1.11

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: changeme
      TZ: "UTC"
    volumes:
      # - mariadb:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      moodle:
        ipv4_address: 10.1.1.12

networks:
    moodle:
        ipam:
            config:
                - subnet: 10.1.1.0/24
        external: false